export const projectData=[
    {
        projectTitle:"EduBlink",
        imgUrl:"",
        tech:"MERN",
        type:"live"
    },
    {
        projectTitle:"EduBlink",
        imgUrl:"",
        tech:"MERN",
        type:"live"
    },
    {
        projectTitle:"EduBlink",
        imgUrl:"",
        tech:"MERN",
        type:"live"
    }
    ,
    {
        projectTitle:"EduBlink",
        imgUrl:"",
        tech:"MERN",
        type:"live"
    },
    ,
    {
        projectTitle:"EduBlink",
        imgUrl:"",
        tech:"MERN",
        type:"live"
    },
    ,
    {
        projectTitle:"EduBlink",
        imgUrl:"",
        tech:"MERN",
        type:"live"
    },
    ,
    {
        projectTitle:"EduBlink",
        imgUrl:"",
        tech:"MERN",
        type:"live"
    },
    ,
    {
        projectTitle:"EduBlink",
        imgUrl:"",
        tech:"MERN",
        type:"live"
    },
    ,
    {
        projectTitle:"EduBlink",
        imgUrl:"",
        tech:"MERN",
        type:"live"
    },
    ,
    {
        projectTitle:"EduBlink",
        imgUrl:"",
        tech:"MERN",
        type:"live"
    },
    ,
    {
        projectTitle:"EduBlink",
        imgUrl:"",
        tech:"MERN",
        type:"live"
    },
    ,
    {
        projectTitle:"EduBlink",
        imgUrl:"",
        tech:"MERN",
        type:"live"
    },
    
    
    

    
    
]